language: php
php: '5.6'
services:
  - elasticsearch
before_install:
  - curl -O https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.4.1/elasticsearch-2.4.1.deb && sudo dpkg -i --force-confnew elasticsearch-2.4.1.deb && sudo service elasticsearch restart
install:
  - composer install
before_script:
  - set -o allexport
  - source .env.testing.example
  - set +o allexport
